blank_issues_enabled: false
contact_links:
    - name: Equicord Support Server
      url: https://discord.gg/5Xh2W87egW
      about: If you need help regarding Equibop or Equicord, please join our support server!
